#!/usr/bin/env bash
# vim:fileencoding=utf-8:foldmethod=marker

# |- Adding Directories to PATH Environment Variable -| #
# |---------------------------------------------------| #


pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        export PATH="${PATH:+"$PATH:"}$1"
    fi
}

# |- General directories ->
pathadd "${HOME}/.bin"
pathadd "${HOME}/.local/bin"

# |- Package directories ->
pathadd "${HOME}/.local/share/cargo/bin"
